---
deployment:
  tasks:
    - export DEPLOYPATH=/home/c17822/public_html
    - export REPOPATH=/home/c17822/et27/public
    - /bin/rm -Rf ${DEPLOYPATH}_old
    - /bin/cp -R ${DEPLOYPATH} ${DEPLOYPATH}_old
    - /bin/rsync -aP --exclude '.git' --exclude '.well-known' --exclude 'index.php' --exclude '/storage' ${REPOPATH} ${DEPLOYPATH} --delete-after
    - /bin/chmod 755 ${DEPLOYPATH}